### ISSUE TITLE
Making a brand new project

### ISSUE THREAD

**Issue by lsfernandes92** [ryanwi/rails7-on-docker#370]
Hello! Firstly, I apologize if this isn't the appropriate place to post this query, as it's more of a question than an issue. I chose to post it here as it might also be a query for others.

I'd like to inquire whether it's possible to initiate a completely new project using some of your files as a template. My intention was to fork your repository and utilize it as a template for my personal projects. Specifically, I'm considering creating a new API-only project using the `rails new` command with the `--api` flag. It would be beneficial if I could leverage some of your files to kickstart this new API project of mine.

Thanks in advance and thanks for sharing!

**Comment by ryanwi** [comment]
Thanks for the question. This project can be used as a Repository template with this link https://github.com/ryanwi/rails7-on-docker/generate

More about templates here: https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-repository-from-a-template

Creating with a template is similar to a fork, just starting fresh instead.

However, then you'd have to convert it to an api-only app. That shouldn't be too bad, probably some guides out there. (slightly outdated https://hashrocket.com/blog/posts/how-to-make-rails-5-api-only)

I'll try it in a branch this week and see if that helps.
